#!/bin/bash
cd /opt/

## Unzip Android Studio's source code
sudo unzip /opt/android-studio-ide-*

## Remove the package zip package at end
sudo rm -r /opt/android-studio-ide-*

## Give permessions to folder to let the built-in update system work
find /opt/android-studio/ -type d -exec chmod 777 {} \;
find /opt/android-studio/ -type f -exec chmod 777 {} \;