#!/bin/bash

# install some dependencies
sudo apt-get install lib32stdc++6 zlib1g zlib1g:i386

cd /opt/

## Download Android Studio from Google's Servers.
wget https://dl.google.com/dl/android/studio/ide-zips/2.1.0.9/android-studio-ide-143.2790544-linux.zip
