#!/bin/bash
cd /opt/

## Unzip Android Studio's source code
sudo unzip /opt/android-studio-ide-*

## Remove the package zip package at end
sudo rm -r /opt/android-studio-ide-*

## Give permessions to folder to let the built-in update system work
find /opt/android-studio/ -type d -exec chmod 777 {} \;
find /opt/android-studio/ -type f -exec chmod 777 {} \;

## Show dialog to complete installation
zenity --info --title 'Android Studio successfully installed' --text '\n This package do not contain an embedded SDK install. \n To get it, go on https://developer.android.com/sdk/index.html and select "GET THE SDK FOR AN EXISTING IDE". \n Thank you!'
